name: Mac Build

on: push

env:
  CCACHE_VERSION: 3.7.7
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  SW_PORTAL_LOGIN: ${{ secrets.PORTAL_LOGIN }}
  
jobs:
  build:

    runs-on: macos-latest
    
    steps:

    - name: run some commands
      run: |
        conda init zsh
        echo "ok"
        sudo chown -R $UID $CONDA
        conda create --name myenv
        conda activate myenv
        conda show
        conda info
