name: Windows Build

on: push

#on:
#  push:
#    branches:
#      - none


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:

    runs-on: windows-latest
    
    steps:

    - uses: actions/checkout@v1

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
    - name: try ssh
      run: |
        Get-Command ssh
        ssh runner@${{ secrets.SSH_HOST }} ls

    - name: try scp
      run: |
        Get-Command scp
        scp runner@brutus.sci.utah.edu:file .
        cat file
