name: Windows Build

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:

    runs-on: windows-latest
    
    steps:

    - uses: actions/checkout@v1

    - name: install rsync
#      run: choco install rsync --no-progress --yes 
      run: choco install rsync openssh --no-progress --yes 

    - name: update path
#      run: echo "C:\Program Files\OpenSSH-Win64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      run: echo "C:\ProgramData\Chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Update PATH
       run: |
             set -xue
             cygpath -w /usr/bin >> $GITHUB_PATH
             cygpath -w /mingw32/bin >> $GITHUB_PATH
      
    - name: try ssh
      run: |
        Get-Command ssh
        Get-Command rsync
        ssh runner@${{ secrets.SSH_HOST }} ls

    - name: try ssh2
      shell: bash
      run: |
        which ssh
        ssh runner@${{ secrets.SSH_HOST }} ls

    - name: rsync
      working-directory: ${{runner.workspace}}
      run: |
        Get-Command ssh
        Get-Command rsync
        rsync -avz  . runner@brutus.sci.utah.edu:github/

#                rsync -avz -e "C:\Progra~1\OpenSSH-Win64\ssh.exe" . runner@brutus.sci.utah.edu:github/

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: D:\\incoming

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: D:\\incoming
      
    - name: list
      shell: bash
      working-directory: ${{runner.workspace}}
      run: mkdir /d/someplace ; echo "contents" > /d/someplace/file.txt ; ls -laR /d/someplace
    
    - uses: actions/upload-artifact@v2
      with:
        name: out-artifact
        path: D:\\someplace
