name: Windows Build

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:

    runs-on: windows-latest
    
    steps:

    - uses: actions/checkout@v1

    - name: list
      shell: bash
      working-directory: ${{runner.workspace}}
      run: ls -laR
    
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{runner.workspace}}\folder
