name: Windows Build WSL

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:

    runs-on: windows-latest
    
    steps:

#C:\Windows\System32\bash.exe

    - name: Setup WSL
      uses: Vampire/setup-wsl@v1.1.0
      with:
        additional-packages:
          rsync
          ssh
      
    - uses: actions/checkout@v1

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
    - name: try out wsl
      shell: wsl-bash {0}
      run: |
        ls

    - name: try out wsl
      shell: wsl-bash {0}
      run: |
        which rsync
        
    - name: rsync
      shell: wsl-bash {0}
      working-directory: ${{runner.workspace}}
      run: |
        mkdir ~/.ssh
        echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
        echo ${{ secrets.KNOWN_HOSTS }} > ~/.ssh/known_hosts
        rsync -v -v -v -avz runner@brutus.sci.utah.edu:file .

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: D:\\incoming

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: D:\\incoming
      
    - name: list
      shell: bash
      working-directory: ${{runner.workspace}}
      run: mkdir /d/someplace ; echo "contents" > /d/someplace/file.txt ; ls -laR /d/someplace
    
    - uses: actions/upload-artifact@v2
      with:
        name: out-artifact
        path: D:\\someplace
